spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${DB_URL:jdbc:postgresql://localhost:5432/postgres }
    username: ${DB_USER:postgres}
    password: ${DB_PASS:root}
server:
  port: 8080

logging:
  level:
    root: info

token:
  secret: ${TOKEN_SECRET:asdff}